# Generated by Django 5.0.3 on 2024-03-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
