# Generated by Django 5.0.3 on 2024-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_alter_contact_color_alter_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#417690', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=10),
        ),
    ]
