# Generated by Django 5.0.3 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_rename_due_date_task_date_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('awaiting_feedback', 'Awaiting Feedback'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
