# Generated by Django 5.0.3 on 2024-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0012_remove_subtask_task_tasksubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='join.TaskSubTask', to='join.subtask'),
        ),
    ]
