# Generated by Django 5.0.3 on 2024-03-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0013_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.DeleteModel(
            name='TaskSubTask',
        ),
    ]
