# Generated by Django 5.0.3 on 2024-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0015_rename_date_task_created_at_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#417690', max_length=7),
        ),
    ]
