# Generated by Django 5.0.3 on 2024-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0017_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='red', max_length=7),
        ),
    ]
