# Generated by Django 5.0.3 on 2024-04-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0019_rename_status_task_stat_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stat',
            field=models.CharField(choices=[('todo', 'Todo'), ('awaitingFeedback', 'Awaiting Feedback'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
