# Generated by Django 5.0.3 on 2024-04-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0021_rename_due_date_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='prio',
        ),
    ]
