# Generated by Django 5.0.3 on 2024-04-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0023_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
    ]
