# Generated by Django 5.0.3 on 2024-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0024_remove_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join.subtask'),
        ),
    ]
