# Generated by Django 5.0.3 on 2024-04-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0026_rename_assigned_to_task_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
