# Generated by Django 5.0.3 on 2024-04-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0028_category_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedTo',
            new_name='assigned_to',
        ),
    ]
