# Generated by Django 5.0.3 on 2024-04-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0029_rename_assignedto_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
    ]
